### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by niclashedam** [madeITBelgium/Laravel-VestaCP#26]
Thank you for your time developing this package. It's much appreciated.
I would like to suggest releasing this package using a valid [Semantic Version](https://semver.org/), such that your peers (.. like me 😄) are able to keep track of releases correctly.

Right now I'm forced to require `dev-master`, which can break my code-base each time something incomplete is pushed to this repository.

If there is anything I can do to help, let me know.

**Comment by madeITBelgium** [comment]
Yes, I know. When there is more support for different APIs I will do this. In the next coming days, I will look into it to release the first version.

**Comment by niclashedam** [comment]
Sorry for bothering you. Is there any update or progress on this issue? Thank you very much in advance.

**Comment by madeITBelgium** [comment]
Hi, @niclashedam my apologies for the delay. I finally find the time to add release versions.
